### ISSUE TITLE
Links broken in Documentation readme.md

### ISSUE THREAD

**Issue by yogeshgadge** [cucumber/cucumber-tmbundle#49]
The bold text below does not link to correct documentation.

> If you are using **RVM** you can set up TextMate to use your RVM settings (read your .rvmrc file) by following **these instructions**.

They are pointing to http://beginrescueend.com and http://beginrescueend.com/integration/textmate/
which goes to some shopping website (http://elizamagazine.com/)

**Comment by DRind** [comment]
The "http://beginrescueend.com" portion of the 2 links should be replaced by "https://rvm.io" (the current RVM site).

**Comment by olleolleolle** [comment]
So, thank you for bringing this up and for clarifying it. There was an existing PR which repaired the domain of the links, at least.

**Comment by olleolleolle** [comment]
Now that the domain is correct, I'll close this Issue.
